apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: skopeo-copy-pipeline
spec:
  tasks: 
    - name: copy
      workspaces: 
        - name: images-url
          workspace: pipeline-copy-workspace
      taskRef:
        name: skopeo-copy