apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-skopeo-copy

---

apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-skopeo-copy
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        pipelineRef:
          name: skopeo-copy-pipeline
        params:
          - name: URL
            value: $(params.URL)