apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-skopeo-copy

---

apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-skopeo-copy
spec:
  params:
    - name: icr-username
      description: Username for the icr
      value: $(params.icr-username)
    - name: icr-password
      description: Password for the icr
      value: $(params.icr-password)
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        serviceAccountName: icr-creds-secret
        pipelineRef:
          name: skopeo-copy-pipeline

---

apiVersion: v1
kind: Secret
metadata:
  name: icr-creds
  annotations:
    tekton.dev/docker-0: https://us.icr.io
type: kubernetes.io/basic-auth
stringData:
  username: $(params.icr-username)
  password: $(params.icr-password)

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: icr-creds-secret
secrets:
  - name: icr-creds